apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsfsfrs-develop-uploads
  namespace: careers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: api-efs
      aws-availability-zone: eu-central-1
