apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-api
  labels:
    type: api-efs
    aws-availability-zone: eu-central-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f320c00e1a8a1416
