# Workflow
 name: 'Chromatic'

 on:
   push:
     branches: [master]
   pull_request:
      branches: [master]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - name: Install npm deps
          run: npm i
          
        - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}